### ISSUE TITLE
Crash while handling Concat

### ISSUE THREAD

**Issue by wesen** [go-go-golems/go-emrichen#1]
Input file: 

```
name: "search-summaries"
short: "Search through summarization index"
long: "Search through the multi-document-summarization index with various filters and field controls"

flags:
  - name: show_vectors
    type: bool
    default: false
    help: "Show vector fields in the output"
  - name: show_keywords
    type: bool
    default: false
    help: "Show keyword fields in the output"
  - name: show_yaml
    type: bool
    default: false
    help: "Show YAML metadata field"
  - name: search
    type: string
    help: "Search text across all text fields"
  - name: title
    type: string
    help: "Search in title field"
  - name: content
    type: string
    help: "Search in content field"
  - name: conversation_snippet
    type: string
    help: "Search in conversation snippet field"
  - name: insight_type
    type: string
    help: "Filter by insight type"
  - name: date_from
    type: date
    help: "Start date (YYYY-MM-DD)"
  - name: date_to
    type: date
    help: "End date (YYYY-MM-DD)"
  - name: goal_category
    type: string
    help: "Filter by goal category"
  - name: goal_timeframe
    type: string
    help: "Filter by goal timeframe"
  - name: has_decisions
    type: bool
    help: "Filter by whether summary has decisions"
  - name: interaction_type
    type: string
    help: "Filter by interaction type"
  - name: primary_focus
    type: string
    help: "Search by primary focus"
  - name: user_id
    type: string
    help: "Filter by user ID"
  - name: thread_id
    type: string
    help: "Filter by thread ID"
  - name: size
    type: int
    default: 10
    help: "Number of results to return"

query:
  _source: !Concat
    - ["title", "content", "conversation_snippet", "date", "insight_type", "metadata", "thread_id", "user_id"]
    - !If
        test: !Var show_vectors
        then: ["title_vector", "content_vector", "conversation_snippet_vector", "metadata_vector"]
        else: !Void
    - !If
        test: !Var show_keywords
        then: ["title_keyword", "content_keyword", "conversation_snippet_keyword"]
        else: !Void
    - !If
        test: !Var show_yaml
        then: ["metadata_yaml"]
        else: !Void
  size: !Var size
  query:
    bool:
      must: !Concat
        - !If
            test: !Exists search
            then:
              - multi_match:
                  query: !Var search
                  fields: [
                    "title^3",
                    "content^2",
                    "conversation_snippet^2",
                    "metadata.primary_focus",
                    "metadata.relationship_challenges",
                    "metadata.specific_areas",
                    "metadata.technical_context"
                  ]
            else: !Void
        - !If
            test: !Exists title
            then:
              - multi_match:
                  query: !Var title
                  fields: ["title", "title_keyword"]
            else: !Void
        - !If
            test: !Exists content
            then:
              - multi_match:
                  query: !Var content
                  fields: ["content", "content_keyword"]
            else: !Void
        - !If
            test: !Exists conversation_snippet
            then:
              - multi_match:
                  query: !Var conversation_snippet
                  fields: ["conversation_snippet", "conversation_snippet_keyword"]
            else: !Void
        - !If
            test: !Exists insight_type
            then:
              - term:
                  insight_type: !Var insight_type
            else: !Void
        - !If
            test: !All
              - !Exists date_from
              - !Exists date_to
            then:
              - range:
                  date:
                    gte: !Var date_from
                    lte: !Var date_to
            else: !Void
        - !If
            test: !Exists goal_category
            then:
              - term:
                  "metadata.goal_category": !Var goal_category
            else: !Void
        - !If
            test: !Exists goal_timeframe
            then:
              - term:
                  "metadata.goal_timeframe": !Var goal_timeframe
            else: !Void
        - !If
            test: !Exists has_decisions
            then:
              - term:
                  "metadata.has_decisions": !Var has_decisions
            else: !Void
        - !If
            test: !Exists interaction_type
            then:
              - term:
                  "metadata.interaction_type": !Var interaction_type
            else: !Void
        - !If
            test: !Exists primary_focus
            then:
              - multi_match:
                  query: !Var primary_focus
                  fields: ["metadata.primary_focus", "metadata.primary_focus.keyword"]
            else: !Void
        - !If
            test: !Exists user_id
            then:
              - term:
                  user_id: !Var user_id
            else: !Void
        - !If
            test: !Exists thread_id
            then:
              - term:
                  thread_id: !Var thread_id
            else: !Void 
```

Crash: 

```
❯ escuse-me examples search-summaries --search lisp
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15e7349]

goroutine 1 [running]:
github.com/go-go-golems/go-emrichen/pkg/emrichen.(*Interpreter).handleConcat(0xc000b08390, 0x10?)
	/home/manuel/code/wesen/corporate-headquarters/go-emrichen/pkg/emrichen/concat.go:19 +0x149
github.com/go-go-golems/go-emrichen/pkg/emrichen.(*Interpreter).Process.func1(0xc000b08390, 0xc00006f118, 0xc00006f150)
	/home/manuel/code/wesen/corporate-headquarters/go-emrichen/pkg/emrichen/emrichen.go:195 +0xddf
github.com/go-go-golems/go-emrichen/pkg/emrichen.(*Interpreter).Process(0xc000b08390, 0xc00075ca00)
	/home/manuel/code/wesen/corporate-headquarters/go-emrichen/pkg/emrichen/emrichen.go:393 +0x266
github.com/go-go-golems/go-emrichen/pkg/emrichen.(*Interpreter).Process.func1(0xc000b08390, 0xc00006f3f0, 0xc00006f428)
	/home/manuel/code/wesen/corporate-headquarters/go-emrichen/pkg/emrichen/emrichen.go:367 +0x168e
github.com/go-go-golems/go-emrichen/pkg/emrichen.(*Interpreter).Process(0xc000b08390, 0xc00075c8c0)
	/home/manuel/code/wesen/corporate-headquarters/go-emrichen/pkg/emrichen/emrichen.go:393 +0x266
github.com/go-go-golems/escuse-me/pkg/cmds.(*ElasticSearchCommand).renderNodeQuery(0xc000018de0, 0xc00006f4a8?)
	/home/manuel/code/wesen/corporate-headquarters/escuse-me/pkg/cmds/cmd.go:143 +0x65
github.com/go-go-golems/escuse-me/pkg/cmds.(*ElasticSearchCommand).RenderQueryToJSON(0xc00079e340?, 0x2088ff3?)
	/home/manuel/code/wesen/corporate-headquarters/escuse-me/pkg/cmds/cmd.go:195 +0x3f
github.com/go-go-golems/escuse-me/pkg/cmds.(*ElasticSearchCommand).RunQueryIntoGlaze(0xc000018de0, {0x2576798, 0xc00022a800}, 0xc000381cc0, 0xc00079e340, {0x2566d40, 0xc000381ae0})
	/home/manuel/code/wesen/corporate-headquarters/escuse-me/pkg/cmds/cmd.go:227 +0xcf
github.com/go-go-golems/escuse-me/pkg/cmds.(*ElasticSearchCommand).RunIntoGlazeProcessor(0xc000018de0, {0x2576798, 0xc00022a800}, 0xc00079e340, {0x2566d40, 0xc000381ae0})
	/home/manuel/code/wesen/corporate-headquarters/escuse-me/pkg/cmds/cmd.go:129 +0x338
github.com/go-go-golems/glazed/pkg/cli.BuildCobraCommandFromGlazeCommand.func1({0x2576798, 0xc00022a800}, 0xc00079e340)
	/home/manuel/code/wesen/corporate-headquarters/glazed/pkg/cli/cobra.go:323 +0x108
github.com/go-go-golems/glazed/pkg/cli.BuildCobraCommandFromCommandAndFunc.func1(0xc000577808, {0xc000845040, 0x0, 0x2})
	/home/manuel/code/wesen/corporate-headquarters/glazed/pkg/cli/cobra.go:184 +0xe59
github.com/spf13/cobra.(*Command).execute(0xc000577808, {0xc000845020, 0x2, 0x2})
	/home/manuel/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x346d460)
	/home/manuel/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/manuel/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.main()
	/home/manuel/code/wesen/corporate-headquarters/escuse-me/cmd/escuse-me/main.go:103 +0x6ff

```
